name: Tests

on:
push:
  paths:
    - 'Module_4/**'
    - '.github/workflows/tests.yaml'
pull_request:
  paths:
    - 'Module_4/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Module_4

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --tb=short