name: Module 4 Tests

on:
  push:
    paths:
      - 'Module_4/**'
      - '.github/workflows/tests.yaml'
  pull_request:
    paths:
      - 'Module_4/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Module_4
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Set environment variables
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

      - name: Create database schema
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -c "
          CREATE TABLE IF NOT EXISTS applicants(
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            program TEXT,
            comments TEXT,
            date_added date,
            url TEXT,
            status TEXT,
            term TEXT,
            us_or_international TEXT,
            gpa real,
            gre real,
            gre_v real,
            gre_aw real,
            degree TEXT,
            llm_generated_program TEXT,
            llm_generated_university TEXT
          );"
          
      - name: Run tests
        run: pytest tests/
