name: Module 4 Tests

on:
  push:
    paths:
      - 'Module_4/**'
      - '.github/workflows/tests.yaml'
  pull_request:
    paths:
      - 'Module_4/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Module_4
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Set environment variables
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

      - name: Create database schema
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -c "
          CREATE TABLE IF NOT EXISTS applicants(
            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            program TEXT,
            comments TEXT,
            date_added date,
            url TEXT,
            status TEXT,
            term TEXT,
            us_or_international TEXT,
            gpa real,
            gre real,
            gre_v real,
            gre_aw real,
            degree TEXT,
            llm_generated_program TEXT,
            llm_generated_university TEXT
          );
          
          INSERT INTO applicants (program, comments, date_added, url, status, term, us_or_international, gpa, gre, gre_v, gre_aw, degree, llm_generated_program, llm_generated_university) VALUES
          ('Computer Science, MIT', 'Strong research background', '2024-01-15', 'https://example.com/1', 'Accepted', 'Fall 2025', 'American', 3.8, 325, 160, 4.5, 'BS', 'Computer Science', 'MIT'),
          ('Physics, Stanford University', 'Good GRE scores', '2024-01-20', 'https://example.com/2', 'Rejected', 'Fall 2025', 'International', 3.7, 320, 155, 4.0, 'BS', 'Physics', 'Stanford University'),
          ('Biology, Harvard University', 'Research experience', '2024-02-01', 'https://example.com/3', 'Accepted', 'Fall 2024', 'American', 3.9, 330, 165, 5.0, 'BS', 'Biology', 'Harvard University'),
          ('Chemistry, UC Berkeley', 'Good fit', '2024-02-10', 'https://example.com/4', 'Waitlisted', 'Spring 2025', 'International', 3.6, 315, 150, 3.5, 'BS', 'Chemistry', 'UC Berkeley'),
          ('Mathematics, Caltech', 'Strong background', '2024-01-25', 'https://example.com/5', 'Accepted', 'Fall 2025', 'American', 4.0, 335, 170, 5.5, 'BS', 'Mathematics', 'Caltech');
          "
          
      - name: Run tests
        run: pytest tests/
